web/router.ex
defmodule ZooInventory.Router do
  use ZooInventory.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ZooInventory do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/about", AboutController, :index
    get "/about/:entity", AboutController, :entity

    resources "/animals", AnimalController
  end

  scope "/api", ZooInventory.Api do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/animals", AnimalController
    end
  end
end

lib/zoo_inventory/encoder.ex
defimpl Poison.Encoder, for: Any do
  def encode(%{__struct__: _} = struct, options) do
    map = struct
          |> Map.from_struct
          |> sanitize_map
    Poison.Encoder.Map.encode(map, options)
  end

  defp sanitize_map(map) do
    Map.drop(map, [:__meta__, :__struct__])
  end
end

lib/zoo_inventory/endpoint.ex
defmodule ZooInventory.Endpoint do
  use Phoenix.Endpoint, otp_app: :zoo_inventory

  socket "/socket", ZooInventory.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :zoo_inventory, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_zoo_inventory_key",
    signing_salt: "VT1PWka7"

  plug ZooInventory.Router
end

lib/zoo_inventory/repo.ex
defmodule ZooInventory.Repo do
  use Ecto.Repo, otp_app: :zoo_inventory
end

web/models/animal.ex
defmodule ZooInventory.Animal do
  use ZooInventory.Web, :model

  schema "animals" do
    field :friendly_name, :string
    field :kingdom, :string
    field :phylum, :string
    field :class, :string
    field :order, :string
    field :family, :string
    field :genus, :string
    field :species, :string

    timestamps
  end

  @required_fields ~w(friendly_name kingdom phylum class order family genus species)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/about_controller.ex
defmodule ZooInventory.AboutController do
  use ZooInventory.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def entity(conn, %{"entity" => entity}) do
    render conn, entity: entity
  end
end

web/controllers/animal_controller.ex
defmodule ZooInventory.AnimalController do
  use ZooInventory.Web, :controller

  alias ZooInventory.Animal

  plug :scrub_params, "animal" when action in [:create, :update]

  def index(conn, _params) do
    animals = Repo.all(Animal)
    render(conn, "index.html", animals: animals)
  end

  def new(conn, _params) do
    changeset = Animal.changeset(%Animal{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"animal" => animal_params}) do
    changeset = Animal.changeset(%Animal{}, animal_params)

    case Repo.insert(changeset) do
      {:ok, _animal} ->
        conn
        |> put_flash(:info, "Animal created successfully.")
        |> redirect(to: animal_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    animal = Repo.get!(Animal, id)
    render(conn, "show.html", animal: animal)
  end

  def edit(conn, %{"id" => id}) do
    animal = Repo.get!(Animal, id)
    changeset = Animal.changeset(animal)
    render(conn, "edit.html", animal: animal, changeset: changeset)
  end

  def update(conn, %{"id" => id, "animal" => animal_params}) do
    animal = Repo.get!(Animal, id)
    changeset = Animal.changeset(animal, animal_params)

    case Repo.update(changeset) do
      {:ok, animal} ->
        conn
        |> put_flash(:info, "Animal updated successfully.")
        |> redirect(to: animal_path(conn, :show, animal))
      {:error, changeset} ->
        render(conn, "edit.html", animal: animal, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    animal = Repo.get!(Animal, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(animal)

    conn
    |> put_flash(:info, "Animal deleted successfully.")
    |> redirect(to: animal_path(conn, :index))
  end
end

web/controllers/api/v1/animal_controller.ex
defmodule ZooInventory.Api.V1.AnimalController do
  use ZooInventory.Web, :controller

  alias ZooInventory.Animal

  def index(conn, _params) do
    animals = Repo.all(Animal)
    render conn, animals: animals
  end
end

web/controllers/page_controller.ex
defmodule ZooInventory.PageController do
  use ZooInventory.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/about_view.ex
defmodule ZooInventory.AboutView do
  use ZooInventory.Web, :view
end

web/views/animal_view.ex
defmodule ZooInventory.AnimalView do
  use ZooInventory.Web, :view
end

web/views/error_view.ex
defmodule ZooInventory.ErrorView do
  use ZooInventory.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule ZooInventory.LayoutView do
  use ZooInventory.Web, :view
end

web/views/page_view.ex
defmodule ZooInventory.PageView do
  use ZooInventory.Web, :view
end

web/templates/about/entity.html.eex
<div class="jumbotron">
  <h2>Today, We Would Like to Thank <i><%= @entity %></i> for Being the World's Greatest Dad!</h2>
</div>

web/templates/about/index.html.eex
<div class="jumbotron">
  <h2>Welcome to the Zoo Inventory Portal</h2>
</div>

<div>
  <h5>A Long and Colorful History</h5>

  <p>
    Since it's creation in late 2015, the Zoo Inventory Portal has been a fault-tolerant workhorse for the staff of a small yet well-funded research facility located in Houston, TX.
  </p>
</div>

web/templates/animal/edit.html.eex
<h2>Edit animal</h2>

<%= render "form.html", changeset: @changeset,
                        action: animal_path(@conn, :update, @animal) %>

<%= link "Back", to: animal_path(@conn, :index) %>

web/templates/animal/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :friendly_name, "Friendly name", class: "control-label" %>
    <%= text_input f, :friendly_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :kingdom, "Kingdom", class: "control-label" %>
    <%= text_input f, :kingdom, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :phylum, "Phylum", class: "control-label" %>
    <%= text_input f, :phylum, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :class, "Class", class: "control-label" %>
    <%= text_input f, :class, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :order, "Order", class: "control-label" %>
    <%= text_input f, :order, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :family, "Family", class: "control-label" %>
    <%= text_input f, :family, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :genus, "Genus", class: "control-label" %>
    <%= text_input f, :genus, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :species, "Species", class: "control-label" %>
    <%= text_input f, :species, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/animal/index.html.eex
<h2>Listing animals</h2>

<table class="table">
  <thead>
    <tr>
      <th>Friendly name</th>
      <th>Kingdom</th>
      <th>Phylum</th>
      <th>Class</th>
      <th>Order</th>
      <th>Family</th>
      <th>Genus</th>
      <th>Species</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for animal <- @animals do %>
    <tr>
      <td><%= animal.friendly_name %></td>
      <td><%= animal.kingdom %></td>
      <td><%= animal.phylum %></td>
      <td><%= animal.class %></td>
      <td><%= animal.order %></td>
      <td><%= animal.family %></td>
      <td><%= animal.genus %></td>
      <td><%= animal.species %></td>

      <td class="text-right">
        <%= link "Show", to: animal_path(@conn, :show, animal), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: animal_path(@conn, :edit, animal), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: animal_path(@conn, :delete, animal), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New animal", to: animal_path(@conn, :new) %>

web/templates/animal/new.html.eex
<h2>New animal</h2>

<%= render "form.html", changeset: @changeset,
                        action: animal_path(@conn, :create) %>

<%= link "Back", to: animal_path(@conn, :index) %>

web/templates/animal/show.html.eex
<h2>Show animal</h2>

<ul>

  <li>
    <strong>Friendly name:</strong>
    <%= @animal.friendly_name %>
  </li>

  <li>
    <strong>Kingdom:</strong>
    <%= @animal.kingdom %>
  </li>

  <li>
    <strong>Phylum:</strong>
    <%= @animal.phylum %>
  </li>

  <li>
    <strong>Class:</strong>
    <%= @animal.class %>
  </li>

  <li>
    <strong>Order:</strong>
    <%= @animal.order %>
  </li>

  <li>
    <strong>Family:</strong>
    <%= @animal.family %>
  </li>

  <li>
    <strong>Genus:</strong>
    <%= @animal.genus %>
  </li>

  <li>
    <strong>Species:</strong>
    <%= @animal.species %>
  </li>

</ul>


<%= link "Edit", to: animal_path(@conn, :edit, @animal) %>
<%= link "Back", to: animal_path(@conn, :index) %>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Zoo Inventory Portal">
    <meta name="author" content="osxi">
    <title>Zoo Inventory Portal</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ul class="nav nav-pills small pull-right">
          <li>
            <a href="<%= about_path(@conn, :index) %>">
              About
            </a>
            <a href="<%= animal_path(@conn, :index) %>">
              Animals
            </a>
          </li>
        </ul>

        <a href="<%= page_path(@conn, :index) %>">
          <span class="logo"></span>
        </a>
      </div>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner %>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>